### ISSUE TITLE
Cannot get my padding right

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/sections#2]
I cannot figure out what is cause my website to be off
@thomasjbradley

**Comment by thomasjbradley** [comment]
There should be a `padding` of `1em` on the `<div>` and a `2em` `padding` on the top & bottom of the `<section>`.

Remove the `inline-block` from the `<body>` because we don’t want it to sit on the same line as another element.

And try removing the unit from the `line-height`, should be just `1.5`.

**Comment by fuen0015** [comment]
Not sure what happened but it's worse

**Comment by thomasjbradley** [comment]
What problems are you running into now?

**Comment by fuen0015** [comment]
Nevermind I fixed it during the catch up class, all is good
